### PR TITLE
maint: add UpgradeState passthrough handlers to 7 Framework resources

### PR DESCRIPTION
**Pull request by rooneyshuman**
## Summary

- Adds `ResourceWithUpgradeState` implementations to the 7 resources migrated from SDKv2 to Plugin Framework in v4.30.0: `grafana_team`, `grafana_service_account`, `grafana_scim_config`, `grafana_public_dashboard`, `grafana_folder_permission`, `grafana_report`, `grafana_dashboard_permission`.
- These handlers are **not invoked** during the initial SDKv2→Framework upgrade — the Framework handles v0→v0 transitions with a built-in passthrough. They exist so that if a schema is later bumped to `Version: 1+`, users who still have v0 state can migrate instead of hitting _"Provider does not support upgrading to version 0 of this resource."_
- Adds an `UpgradeState for SDKv2→Framework migrations` section to the migration playbook explaining when the handler fires, why to register it proactively, and what to do if a future structural schema change makes the simple passthrough unsafe.
- Fixes misleading comments in all 7 files (previously said "prevent a provider crash" which implied the handler was called during the upgrade; it is not).

## Test plan

- [ ] `go build ./...` passes (no new compilation errors)
- [ ] No new `ResourceWithUpgradeState` implementations needed — these cover all resources migrated in v4.29.2/v4.30.0
- [ ] Spot-check: `go test ./internal/resources/grafana/... -run TestUnit` passes

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

File: internal/resources/grafana/resource_dashboard_public.go [hunk 1]
```diff
@@ -18,9 +18,10 @@ import (
 )
 
 var (
-	_ resource.Resource                = &publicDashboardResource{}
-	_ resource.ResourceWithConfigure   = &publicDashboardResource{}
-	_ resource.ResourceWithImportState = &publicDashboardResource{}
+	_ resource.Resource                  = &publicDashboardResource{}
+	_ resource.ResourceWithConfigure     = &publicDashboardResource{}
+	_ resource.ResourceWithImportState   = &publicDashboardResource{}
+	_ resource.ResourceWithUpgradeState  = &publicDashboardResource{}
```
Comment (Duologic) [inline internal/resources/grafana/resource_dashboard_public.go:24]:
```suggestion
	_ resource.ResourceWithUpgradeState = &publicDashboardResource{}
```

There's a space too much I think, might want to check other files as well.

**Review by Duologic — CHANGES_REQUESTED** [review]
> Fixes misleading comments in all 7 files (previously said "prevent a provider crash" which implied the handler was called during the upgrade; it is not).

I can't see which comments said that.

The `UpgradeState` fn is duplicated in every resource but that's fine as it serves as scaffolding for future migrations.

Having a quick look at resources migrated from SDKv2 to Framework:
- `grafana_annotation` (v4.28.2) — missing UpgradeState scaffolding
- `grafana_alerting_message_template` (v4.28.2) — missing UpgradeState scaffolding
- `grafana_playlist` (v4.29.0) — missing UpgradeState scaffolding
- `grafana_scim_config` (v4.29.0) — covered by this PR
- `grafana_folder_permission` (v4.29.0) — covered by this PR
- `grafana_team` (v4.29.1) — covered by this PR
- `grafana_dashboard_public` (v4.30.0) — covered by this PR
- `grafana_dashboard_permission` (v4.30.0) — covered by this PR
- `grafana_service_account` (v4.30.0) — covered by this PR
- `grafana_report` (v4.30.0) — covered by this PR

Datasources migrated from SDKv2 to Framework (no UpgradeState needed — datasources don't persist state between runs):
- `cloud_ips` (v4.28.1)
- `cloud_organization` (v4.28.1)
- `grafana_team` (v4.29.0)

**Comment by Duologic** [comment]
This PR won't fix the crash in #2695 — the v0 handlers are never called during v0→v0 transitions (the Framework's passthrough runs first), and even with a version bump, the `UnmarshalWithOpts` call is identical in both paths. See #2695 (comment) for the full analysis.

The PR is still useful as scaffolding for a future fix.
